executable = 
arguments = 

transfer_input_files = 

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

log           = logs/job.$(Cluster).$(Process).log
error         = logs/job.$(Cluster).$(Process).error
output        = logs/job.$(Cluster).$(Process).out

+JobDurationCategory = "Medium"
requirements   = (OSGVO_OS_STRING == "RHEL 7")

request_cpus   = 1
request_memory = 512MB
request_disk   = 512MB

queue 1
